version: '3'

services:
  network:
    image: centos:7
    ports:
      - 127.0.0.1:20389:1389
      - 127.0.0.1:20636:1636
      - 127.0.0.1:8000:8000
      - 127.0.0.1:8080:8080
      - 127.0.0.1:8180:8180
      - 127.0.0.1:10636:10636
      - 127.0.0.1:10025:10025
    command: ["sleep", "infinity"]
    stop_signal: SIGKILL
    networks:
      - identity

  postfix:
    image: docker.artifacts.rackspace.net/postfix
    environment:
      POSTFIX_PORT: 10025
    network_mode: "service:network"

  openldap:
    image: docker.artifacts.rackspace.net/openldap
    volumes:
      - ./openldap/config:/config
      - ./openldap/ldif:/data
    network_mode: "service:network"

  cadir:
    image: docker.artifacts.rackspace.net/ca-directory
    volumes:
      - ./ldap/config:/config
      - ./ldap/ldif:/data
    network_mode: "service:network"

  cloudfeeds:
    image: docker.artifacts.rackspace.net/cloud-feeds
    environment:
      TOMCAT_HTTP_PORT: 8180
      TOMCAT_AJP_PORT: 8109
      TOMCAT_SHUTDOWN_PORT: 8105
    network_mode: "service:network"

  repose:
    image: docker.artifacts.rackspace.net/repose
    environment:
      IDENTITY_HOST: ${HOSTIP}
      IDENTITY_PORT: 8083
    volumes:
      - ./repose/config:/etc/repose-build/config
    network_mode: "service:network"

  dynamodb:
    image: docker.artifacts.rackspace.net/dynamodb
    volumes:
      - ./dynamodb/config:/config
      - ./dynamodb/data:/data
    network_mode: "service:network"

networks:
  identity:
    driver: bridge
