edir:
    image: docker.ciidentity.com/e-directory-instance
    ports:
        - 20636:636
        - 10389:389

directory:
    image: docker.ciidentity.com/ca-directory-instance
    ports:
        - 10636:10636
    environment:
        NEXUS_HOST: http://d-build1.iad2.corp.rackspace.com:8100
        VERSION: LATEST

identity:
    image: docker.ciidentity.com/cloud-identity-instance
    ports:
        - 8079:8080
    links:
        - edir
        - directory
    environment:
        NEXUS_HOST: http://d-build1.iad2.corp.rackspace.com:8100
        VERSION: LATEST
        SPRING_PROFILE: LDAP
        EDIRECTORY_PORT: 636

repose:
    image: docker.ciidentity.com/repose-instance:8.7.3.0
    links:
        - identity
    ports:
        - 8082:8080
    environment:
        NEXUS_HOST: http://d-build1.iad2.corp.rackspace.com:8100
        VERSION: LATEST
        IDENTITY_HOSTNAME: identity

identity_perf_agent:
    image: "ubuntu:16.04"
    volumes: 
        - $PWD/identity-perf-agent:/root/identity-perf-agent
    command: sleep 10d
    links:
        - repose

scheduler:
    image: "ubuntu:16.04"
    volumes:
        - $PWD/scheduler:/root/scheduler
    ports:
        - 9080:8080
        - 3306:3306
    command: sleep 10d

controller:
    image: "ubuntu:16.04"
    volumes:
        - $PWD/controller:/root/controller
    volumes_from: 
        - identity_perf_agent
        - scheduler
    links:
        - identity_perf_agent
        - scheduler
    command: sleep 10d
