//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.06 at 01:05:24 PM CDT 
//


package com.rackspace.api.idm.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UserPasswordCredentials complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserPasswordCredentials">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="newPassword" type="{http://idm.api.rackspace.com/v1.0}UserPassword" minOccurs="0"/>
 *         &lt;element name="currentPassword" type="{http://idm.api.rackspace.com/v1.0}UserPassword" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="verifyCurrentPassword" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserPasswordCredentials", propOrder = {
    "newPassword",
    "currentPassword"
})
public class UserPasswordCredentials {

    protected UserPassword newPassword;
    protected UserPassword currentPassword;
    @XmlAttribute(name = "verifyCurrentPassword")
    protected Boolean verifyCurrentPassword;

    /**
     * Gets the value of the newPassword property.
     * 
     * @return
     *     possible object is
     *     {@link UserPassword }
     *     
     */
    public UserPassword getNewPassword() {
        return newPassword;
    }

    /**
     * Sets the value of the newPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserPassword }
     *     
     */
    public void setNewPassword(UserPassword value) {
        this.newPassword = value;
    }

    /**
     * Gets the value of the currentPassword property.
     * 
     * @return
     *     possible object is
     *     {@link UserPassword }
     *     
     */
    public UserPassword getCurrentPassword() {
        return currentPassword;
    }

    /**
     * Sets the value of the currentPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserPassword }
     *     
     */
    public void setCurrentPassword(UserPassword value) {
        this.currentPassword = value;
    }

    /**
     * Gets the value of the verifyCurrentPassword property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVerifyCurrentPassword() {
        return verifyCurrentPassword;
    }

    /**
     * Sets the value of the verifyCurrentPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVerifyCurrentPassword(Boolean value) {
        this.verifyCurrentPassword = value;
    }

}
