//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.14 at 12:12:39 PM CDT 
//


package com.rackspace.idm.faults;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.rackspace.idm.faults package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _IdmFault_QNAME = new QName("http://docs.rackspacecloud.com/idm/api/v1.0", "idmFault");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.rackspace.idm.faults
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IdmFault }
     * 
     */
    public IdmFault createIdmFault() {
        return new IdmFault();
    }

    /**
     * Create an instance of {@link Forbidden }
     * 
     */
    public Forbidden createForbidden() {
        return new Forbidden();
    }

    /**
     * Create an instance of {@link MissingUsername }
     * 
     */
    public MissingUsername createMissingUsername() {
        return new MissingUsername();
    }

    /**
     * Create an instance of {@link UsernameConflict }
     * 
     */
    public UsernameConflict createUsernameConflict() {
        return new UsernameConflict();
    }

    /**
     * Create an instance of {@link Unauthorized }
     * 
     */
    public Unauthorized createUnauthorized() {
        return new Unauthorized();
    }

    /**
     * Create an instance of {@link UserDisabled }
     * 
     */
    public UserDisabled createUserDisabled() {
        return new UserDisabled();
    }

    /**
     * Create an instance of {@link ServiceUnavailable }
     * 
     */
    public ServiceUnavailable createServiceUnavailable() {
        return new ServiceUnavailable();
    }

    /**
     * Create an instance of {@link EmailConflict }
     * 
     */
    public EmailConflict createEmailConflict() {
        return new EmailConflict();
    }

    /**
     * Create an instance of {@link ItemNotFound }
     * 
     */
    public ItemNotFound createItemNotFound() {
        return new ItemNotFound();
    }

    /**
     * Create an instance of {@link CustomerIdConflict }
     * 
     */
    public CustomerIdConflict createCustomerIdConflict() {
        return new CustomerIdConflict();
    }

    /**
     * Create an instance of {@link BadRequest }
     * 
     */
    public BadRequest createBadRequest() {
        return new BadRequest();
    }

    /**
     * Create an instance of {@link PasswordValidationFault }
     * 
     */
    public PasswordValidationFault createPasswordValidationFault() {
        return new PasswordValidationFault();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdmFault }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.rackspacecloud.com/idm/api/v1.0", name = "idmFault")
    public JAXBElement<IdmFault> createIdmFault(IdmFault value) {
        return new JAXBElement<IdmFault>(_IdmFault_QNAME, IdmFault.class, null, value);
    }

}
